### ISSUE TITLE
Bonding Curve API Documention

### ISSUE THREAD

**Issue by cgdusek** [onomyprotocol/solonomy#3]
Research and implement smart contract documentation platform then document the Bonding Curve Contract and the Gravity contract.

**Comment by cgdusek** [comment]
https://github.com/onomyprotocol/solonomy/blob/main/contracts/BondingNOM.sol

**Comment by cgdusek** [comment]
We have a documentation repo:
https://github.com/onomyprotocol/documentation
Lets keep documentation there and link to it on the solonomy readme

**Comment by cgdusek** [comment]
https://docs.soliditylang.org/en/develop/natspec-format.html

**Comment by cgdusek** [comment]
So, thinking we can write the comments in natspec on the contract and then use soldoc to publish them to gitbook https://github.com/HQ20/soldoc

**Comment by tpikachu** [comment]
![image](https://user-images.githubusercontent.com/46133358/110356839-e2950a00-7ff7-11eb-9b9d-81f897e3d82a.png)

**Comment by tpikachu** [comment]
Due to this error, I'm going to change `payable(msg.sender)` to `address(msg.sender)`.

**Comment by cgdusek** [comment]
> Due to this error, I'm going to change `payable(msg.sender)` to `address(msg.sender)`.

Sounds good, thanks for catching that
